version: '3.8'
services:
  s_webapi:
    build:
      context: ./
      dockerfile: ./src/WebAPI/Dockerfile
    restart: always
    ports:
      - "5008:5008"
    networks:
      - localnetwork

  s_webui:
    build:
      context: ./
      dockerfile: ./src/WebUI/Dockerfile
    restart: always
    ports:
      - "5009:5009"
    networks:
      - localnetwork

networks:
  localnetwork:
