#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./src/WebUI/WebUI.csproj", "src/WebUI/"]
COPY ["./CoreFramework/CoreFramework.Application/CoreFramework.Application.csproj", "CoreFramework/CoreFramework.Application/"]
COPY ["./CoreFramework/CoreFramework.CrossCuttingConsern/CoreFramework.CrossCuttingConsern/CoreFramework.CrossCuttingConsern.csproj", "CoreFramework/CoreFramework.CrossCuttingConsern/CoreFramework.CrossCuttingConsern/"]
COPY ["./CoreFramework/CoreFramework.Security/CoreFramework.Security.csproj", "CoreFramework/CoreFramework.Security/"]
COPY ["./CoreFramework/CoreFramework.Persistence/CoreFramework.Persistence.csproj", "CoreFramework/CoreFramework.Persistence/"]
RUN dotnet restore "src/WebUI/WebUI.csproj"
COPY . .
WORKDIR "/src/src/WebUI"
RUN dotnet build "WebUI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebUI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebUI.dll"]
